name: Installing Python

on: [push]

jobs:
  #
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        py-version: [python-version: 3.11, python-version: 3.12, python-version: '3.10']
    steps:
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        '${{ matrix.py-version }}'
        
